name: Deploy Cloudflare Worker

on:
  pull_request:
    branches:
      - main
    paths:
      - 'worker/**'
  push:
    branches:
      - main
    paths:
      - 'worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Install dependencies
        working-directory: worker/winter-star-ad97
        run: npm install

      - name: Deploy to Cloudflare Worker (Preprod)
        if: github.event_name == 'pull_request'
        working-directory: worker/winter-star-ad97
        run: wrangler deploy --env preprod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Worker (Production)
        if: github.event_name == 'push'
        working-directory: worker/winter-star-ad97
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
