name: Deploy Cloudflare Worker
on:
  push:
    branches:
      - main
      - deployment-pipeline
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Install dependencies
        run: cd worker && npm install

      - name: Deploy to Cloudflare Workers
        run: cd worker && wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
